import Head from 'next/head'
import { Inter } from 'next/font/google'
import { MainContainer } from '@/components/layout/main-container';
import { Background } from '@/components/layout/common/background';
import { AnimatePresence, motion } from 'framer-motion';
import { GameCard } from '@/components/game/game-card';
import { GameCardParallax } from '@/components/game/game-card-parallax';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer>
        <main>
          <Background image='/assets/games/elden-ring.jpg'/>

          <section className='mt-10'>
            <div className='flex flex-row gap-4 justify-center'>
              
              <GameCardParallax className='xs:w-[255px] sm:w-[400px] md:w-[500px] lg:w-[700px] xl:w-[1000px] rounded-xl' src='/assets/games/control.jpg' alt='control-2'/>

              <div>
                <motion.p
                  className='text-white font-bold mb-4 xs:text-lg sm:text-2xl md:text-3xl lg:text-4xl xl:text-5xl'
                  initial={{opacity: 0}}
                  animate={{opacity: 1,}}
                  transition={{duration: 0.2}}
                  exit={{
                    opacity: 0,
                  }}
                >
                  Endless Games
                </motion.p>

                <motion.p
                  className='text-white
                              xs:text-xs xs:w-[155px] xs:h-[135px] sm:text-sm sm:w-[200px] sm:h-[200px] md:text-md md:w-[250px]
                              md:h-[250px] lg:text-lg lg:w-[300px] lg:h-[350px] xl:text-xl xl:w-96 overflow-y-auto'
                  initial={{opacity: 0}}
                  animate={{opacity: 1}}
                  transition={{duration: 0.3}}
                  exit={{
                    opacity: 0,
                  }}
                >
                  Step into a world of infinite possibilities with our vast selection of games. With countless genres,
                  themes, and storylines to choose from, there's no limit to the gaming experiences you can explore.
                  Discover the latest and greatest titles or revisit beloved classics, all at your fingertips. From
                  action-packed adventures to immersive role-playing games, there's something for everyone in our ever-expanding
                  library. The possibilities are endless, and the adventure never stops.
                </motion.p>
              </div>
            </div>
          </section>

          <section className='mt-20 mb-20'>
            <div className='flex flex-row gap-4 justify-center'>
              <div>
                <motion.p
                  className='text-white font-bold text-5xl mb-4 xs:text-lg xs: sm:text-2xl md:text-3xl lg:text-4xl'
                  initial={{opacity: 0}}
                  animate={{opacity: 1}}
                  transition={{duration: 0.2}}
                  exit={{
                    opacity: 0,
                  }}
                >
                  Go On Adventures
                </motion.p>
                  
                <motion.p
                  className='text-white text-lg
                              xs:text-xs xs:w-[140px] xs:h-[120px] sm:text-sm sm:w-[200px] sm:h-[200px]
                              md:text-lg md:w-[250px] md:h-[250px] lg:text-xl lg:w-[300px] lg:h-[350px]
                              xl:text-xl xl:w-96 xl:h-full
                              overflow-y-auto'
                  initial={{opacity: 0}}
                  animate={{opacity: 1}}
                  transition={{duration: 0.3}}
                  exit={{
                    opacity: 0,
                  }}
                >
                  Embark on endless adventures and explore captivating storylines with our wide range of games.
                  Immerse yourself in fantastic worlds where you can be anyone or anything you want, and experience
                  heart-pounding action, romance, drama, and suspense. With so many different genres to choose from,
                  including RPGs, adventure games, puzzle games, and more, you'll never run out of stories to discover.
                  And if you're looking for something more competitive, dive into the fast-paced world of multiplayer
                  FPS games, where you can team up with friends or go head-to-head with rivals for the ultimate adrenaline
                  rush. With endless possibilities and engaging gameplay, our games are sure to provide hours of fun and
                  entertainment for players of all ages and skill levels.
                </motion.p>
              </div>
              
              <GameCardParallax className='xs:w-[255px] sm:w-[400px] md:w-[500px] lg:w-[700px] xl:w-[1000px] rounded-xl' duration={0.7} src='/assets/games/gta-v.jpg' alt='control-2'/>
            </div>
          </section>

          <section className='flex flex-row gap-4 justify-center mb-10'>
            <motion.div
              className='flex justify-center rounded-xl text-white font-bold text-5xl border-2 rounded-xl px-4 py-4
                          xs:w-[200px] xs:h-[50px] sm:w-[250px] sm:h-[80px] lg:w-[300px]'
              initial={{scale: 0.5}}
              animate={{scale: 1}}
              transition={{duration: 0.3}}
              whileHover={{scale: 1.1}}
              exit={{
                opacity: 0,
                scale: 0.5
              }}
            >
              <Link
                href='/store'
                className='w-full h-full flex justify-center items-center xs:text-xl sm:text-2xl md:text-3xl'
              >
                Start Shopping
              </Link>
            </motion.div>
          </section>
        </main>
      </MainContainer>
    </>
  )
}
